build intermediate image

diff --git a/.github/workflows/build-hald-image.yml b/.github/workflows/build-hald-image.yml
--- a/.github/workflows/build-hald-image.yml
+++ b/.github/workflows/build-hald-image.yml
@@ -12,9 +12,154 @@ env:
   IMAGE_REGISTRY: docker.io/${{ github.repository_owner }}
 
 jobs:
+  build-shared:
+    name: Build and push shared stage
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      packages: write
+      id-token: write
+    strategy:
+      fail-fast: false
+      matrix:
+        major_version:
+          - 44
+        include:
+          - major_version: 44
+            is_latest_version: true
+            is_stable_version: true
+            is_next_version: true
+
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v7
+
+      - name: Enable sigstore
+        shell: bash
+        run: |
+          sudo mkdir -p /etc/containers/registries.d
+          sudo touch /etc/containers/registries.d/"${{ github.repository_owner }}".yaml
+          echo "docker:" | sudo tee /etc/containers/registries.d/"${{ github.repository_owner }}".yaml
+          echo "  ${{ env.IMAGE_REGISTRY }}:" | sudo tee -a /etc/containers/registries.d/"${{ github.repository_owner }}".yaml
+          echo "    use-sigstore-attachments: true" | sudo tee -a /etc/containers/registries.d/"${{ github.repository_owner }}".yaml
+
+      - name: Install cosign
+        uses: sigstore/cosign-installer@main
+
+      - name: Gather environment variables
+        shell: bash
+        run: |
+          echo "SOURCE_ORG=fedora" >> $GITHUB_ENV
+          echo "SOURCE_IMAGE=fedora" >> $GITHUB_ENV
+
+      - name: Generate tags
+        id: generate-tags
+        shell: bash
+        run: |
+          FVER="${{ matrix.major_version }}"
+          SRC="docker://${{ env.IMAGE_REGISTRY }}/timesinkc"
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            echo "PR_TAG=${SRC}:${{ env.IMAGE_NAME }}-pr-${{ github.event.number }}" >> $GITHUB_ENV
+          else
+            echo "VER_TAG=${SRC}:shared-${FVER}" >> $GITHUB_ENV
+            echo "DATE_TAG=${SRC}:shared-${FVER}-$(date +%Y%m%d)" >> $GITHUB_ENV
+          fi
+
+      - name: Retrieve keys
+        run: |
+          mkdir -p /tmp/certs || echo "dir exists"
+          echo "${{ secrets.SIGNING_SECRET }}" > /tmp/certs/SIGNING_SECRET.key
+
+      - name: Setup podman in podman
+        shell: bash
+        run: |
+          podman create --privileged -ti --name build \
+            --mount type=bind,src=/tmp/certs,dst=/tmp/certs \
+            --mount type=bind,src=scripts,dst=/scripts \
+            --mount type=bind,src=files,dst=/files \
+            --mount type=bind,src=/etc/containers/registries.d,dst=/etc/containers/registries.d \
+            --mount type=bind,src=./Containerfile,dst=/Containerfile \
+            quay.io/podman/stable:latest
+          podman start build
+
+      - name: Verify hald container
+        shell: bash
+        run: |
+          HALD_CONTAINER="docker.io/nostale3210/hald-utils:latest"
+          if ! cosign verify --insecure-ignore-tlog --key hald.pub "$HALD_CONTAINER";
+          then
+            exit 1
+          fi
+          podman exec --privileged build \
+            podman pull "$HALD_CONTAINER"
+
+      - name: Build image
+        shell: bash
+        run: |
+          podman exec --privileged build \
+            podman build --build-arg=SOURCE_ORG="${{ env.SOURCE_ORG }}" \
+            --build-arg=SOURCE_IMAGE="${{ env.SOURCE_IMAGE }}" \
+            --build-arg=FEDORA_MAJOR_VERSION="${{ matrix.major_version }}" \
+            --pull=newer \
+            --target=shared \
+            --tag="localhost/shared:latest" \
+            --annotation=io.github.containers.compression.zstd=true \
+            --label=io.github.containers.compression.zstd=true \
+            -f ./Containerfile
+
+      - name: Push image
+        shell: bash
+        run: |
+          IMAGE="localhost/shared:latest"
+          COMPRESSION_FORMAT="zstd"
+
+          podman exec --privileged build \
+            podman login --username="${{ github.actor }}" \
+            --password="${{ secrets.DOCKERHUB_TOKEN }}" docker.io
+
+          push_pr() {
+            FAILED=()
+            podman exec --privileged build \
+              podman push "$IMAGE" "${{ env.PR_TAG }}" --force-compression \
+              --compression-format="$COMPRESSION_FORMAT" --tls-verify=true || FAILED+=("PR")
+            if [[ "${{ github.event_name }}" == "pull_request" && "${FAILED[*]}" == *"PR"* ]]; then
+              echo "PR failed!" && return 1
+            else return 0; fi
+          }
+
+          push_tag() {
+            TAG="$1"
+            FAILED=()
+            podman exec --privileged build \
+              podman push "$IMAGE" "${TAGS[$TAG]}" \
+              --compression-format="$COMPRESSION_FORMAT" --tls-verify=true --force-compression \
+              --sign-by-sigstore-private-key=/tmp/certs/SIGNING_SECRET.key || FAILED+=("$TAG")
+            if [[ "${FAILED[*]}" == *"VER"* && "${{ github.event_name }}" != "pull_request" ]]; then
+              echo "Pushing "${TAGS[$TAG]}" failed!" && return 1
+            elif [[ "${FAILED[*]}" == *"DATE"* && "${{ github.event_name }}" != "pull_request" ]]; then
+              echo "Pushing "${TAGS[$TAG]}" failed!" && return 1
+            else echo ""${TAGS[$TAG]}" pushed successfully!" && return 0; fi
+          }
+
+          declare -A -r TAGS=(
+            ["VER"]="${{ env.VER_TAG }}"
+            ["DATE"]="${{ env.DATE_TAG }}"
+          )
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then push_pr;
+          else
+            for TAG in "${!TAGS[@]}"; do
+              for try in {1..3}; do
+                if push_tag "$TAG"; then break; fi
+                echo "Try $try out of 3 failed!"
+                sleep 15
+              done
+            done
+          fi
+
   build-and-push:
     name: Build and push image
     runs-on: ubuntu-latest
+    needs: build-shared
     permissions:
       contents: read
       packages: write
@@ -113,17 +258,6 @@ jobs:
           sudo rm -rf /usr/local/.ghcup
           df -h /
 
-      - name: Verify hald container
-        shell: bash
-        run: |
-          HALD_CONTAINER="docker.io/nostale3210/hald-utils:latest"
-          if ! cosign verify --insecure-ignore-tlog --key hald.pub "$HALD_CONTAINER";
-          then
-            exit 1
-          fi
-          podman exec --privileged build \
-            podman pull "$HALD_CONTAINER"
-
       - name: Build image
         shell: bash
         run: |
@@ -132,6 +266,7 @@ jobs:
             --build-arg=SOURCE_IMAGE="${{ env.SOURCE_IMAGE }}" \
             --build-arg=FEDORA_MAJOR_VERSION="${{ matrix.major_version }}" \
             --build-arg=IMAGE_FLAVOR="${{ matrix.build_target }}" \
+            --build-arg=SHARED_IMAGE=docker.io/nostale3210/timesinkc:shared-"${{ matrix.major_version }}" \
             --pull=newer --secret=id=AKMOD_PRIVKEY,src=/tmp/certs/AKMOD_PRIVKEY \
             --target="${{ matrix.desktop }}-${{ matrix.build_target }}" \
             --tag="localhost/timesink:latest" \
